title: CAIMS 2023
preposition: at
description: >-
  Canadian Applied and Industrial Mathematics Society Annual Meeting, Fredericton, New Brunswick, Canada
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://caims2023.github.io" # the base hostname & protocol for the site

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/
  minisymposia:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: minisymposia
    values:
      layout: minisymposium
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: CAIMS2023
      img: 'caims-logo.svg'
      url: 'https://caims.ca/'
    links:
      - name: Registration
        relative_url: /registration/
      - name: Accomodation
        relative_url: /accomodation/
      - name: Committees
        relative_url: "/committees.html"
      - name: Minisymposia
        relative_url: /minisymposia/
        layout: minisymposia-overview
      - name: Speakers
        relative_url: /speakers/
        layout: speaker-overview
      - name: Talks
        relative_url: /talks/
      - name: Program
        relative_url: /program/
      - name: Rooms
        relative_url: /rooms/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    logo:
      img: 'unbcampus.png'
    # links appearing along the bottom of main page
    links:
      #      - name: Program
      #  relative_url: /program/
      #- name: How to get there
      #  relative_url: /location/
      #- name: Tickets
      #  disabled: true
      #  absolute_url: ''

  # Information boxes
  info_bars:
    - title: Registration is Open!
      color: primary
      main_only: false
      text: |
        "Register [here](/registration/index.html) by May 15, 2023 for an early-bird discount."
    - title: Call for EDI volunteers and panelists
      color: primary
      main_only: true
      text: |
        "We are accepting volunteers and nominations for panelists for the OMNI/RÉUNIS-CAIMS Equity, Diversity and Inclusion (EDI) panel, which will occur on Wednesday June 14 2pm-3.40pm at the CAIMS meeting in Fredericton. [For more details, and to apply see here:](https://docs.google.com/forms/d/e/1FAIpQLSe358wMK7zdZgtwICTT9lx19C256LPGX3yPQA69wA3SP_fRtQ/viewform?usp=sf_link)"


  # Live indications
  live:
    date: 12.06.2023
    timezone: GMT-3
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  map:
    # Initial map center point
    home_coord: 45.94759434520442, -66.64360844053535
    # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    # The following do match the Bootstrap design not too badly:
    #   - Hydda.Full
    #   - Thunderforest.Neighbourhood
    #   - Esri.WorldTopoMap
    map_provider: "OpenStreetMap.Mapnik"
    default_zoom: 17

  talks:
    # Talk categories
    main_categories:
      - name: Plenaries
        color: info
      - name: MS
        color: warning
      - name: Prize talks
        color: success
      - name: Breaks
        color: dark
      - name: Special Sessions
        color: alert


    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page
    map: false

  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
